### ISSUE TITLE
Požadovaná verze Pythonu

### ISSUE THREAD

**Issue by daliboris** [DCGM/discourseer#2]
V pokynech se píše, že je potřeba Python verze `3.8 a vyšší`., na PC mám nainstalovanou verzi `3.11`.

Po spuštění příkazu `pip install -r requirements.txt` se objeví chybová zpráva:

```console
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.8,<3.11; 0.2.0 Requires-Python >=3.8,<3.11; 0.2.1 Requires-Python >=3.8,<3.11; 0.2.2 Requires-Python >=3.8,<3.11; 0.2.3 Requires-Python >=3.8,<3.11; 0.2.4 Requires-Python >=3.8,<3.11; 0.4.0 Requires-Python >=3.8,<3.11; 0.4.1 Requires-Python <3.11,>=3.9
ERROR: Could not find a version that satisfies the requirement irrcac (from versions: none)
ERROR: No matching distribution found for irrcac
```

Znamená to, že je potřeba mít Python pouze ve verzi `3.8`, `3.9`, nebo `3.10`?

**Comment by vlachvojta** [comment]
Knihovna `irrcac` není v současné době podporována pro Python 3.11. 
`irrcac v0.4.1` (poslední verze) by měla být podporována pro Python 3.9 a 3.10.

Nejjednodušší oprava se tedy zdá bý nainstalovat např. Python 3.10. (na počítači lze mít i více verzí naráz)
Je to z Vaší strany možné, nebo se mám pokusit zajistit jiné řešení?
